# 우유와 요거트를 동시에 구입한 장바구니 있는지

# with m2 as (SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE NAME='Yogurt' OR NAME='Milk')
# GROUP BY CART_ID
# HAVING NAME='Yogurt' and NAME='Milk'

SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Yogurt','Milk')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME)=2
ORDER BY CART_ID

# SELECT CART_ID
# FROM CART_PRODUCTS
# GROUP BY CART_ID
# HAVING COUNT(CART_ID)>=2
# ORDER BY CART_ID

# SELECT CART_ID
# FROM CART_PRODUCTS
# GROUP BY CART_ID
# HAVING NAME='Yogurt' and NAME='Milk'
# ORDER BY CART_ID