# ITEM_TREE 에서 값(ITEM_ID) 구하면 ITEM_INFO로 정보 뽑으면 됨

WITH CH as(SELECT ITEM_ID, CASE
WHEN ITEM_ID IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE) THEN 1
ELSE 0
END AS jj
FROM ITEM_TREE)

SELECT a.ITEM_ID,a.ITEM_NAME,a.RARITY
FROM ITEM_INFO a
JOIN CH b
ON a.ITEM_ID=b.ITEM_ID
WHERE  b.jj=0
ORDER BY ITEM_ID DESC