-- 코드를 입력하세요
# 자동차 종류가 '세단' 또는 'SUV' 중 
#2022년 11월 1일부터 2022년 11월 30일까지 대여 가능 2번째에서 없어야 함
#30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차 3번쨰
# ORDER BY 금액 DESC, 종류, ID DESC
# 넣어야 할 아이디
with carFee as(
SELECT CAR_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE (CAR_TYPE='세단' or CAR_TYPE='SUV') and DURATION_TYPE='30일 이상'),
# 빼야할 아이디
outID as(
SELECT a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID=b.CAR_ID
WHERE b.START_DATE <= '2022-11-30' 
AND b.END_DATE >= '2022-11-01' 
AND (a.CAR_TYPE='세단' OR a.CAR_TYPE='SUV'))



SELECT a.CAR_ID, a.CAR_TYPE, FLOOR((a.DAILY_FEE*(100-DISCOUNT_RATE)/100*30)) as FEE
FROM  CAR_RENTAL_COMPANY_CAR a
LEFT JOIN outID c on a.CAR_ID=c.CAR_ID
RIGHT JOIN carFee d on a.CAR_TYPE=d.CAR_TYPE
WHERE c.CAR_ID IS NULL 
and (a.DAILY_FEE*(100-DISCOUNT_RATE)/100*30) BETWEEN 500000 and 2000000
ORDER BY FEE DESC, a.CAR_TYPE, a.CAR_ID DESC


