# 입양을 간 기록은 있는데 들어온 기록은 없음
# OUT에는 있는데 IN에는 없음
SELECT ANIMAL_ID,NAME
FROM ANIMAL_OUTS O
WHERE NOT EXISTS ( SELECT ANIMAL_ID,NAME
                  FROM ANIMAL_INS I
                  WHERE I.ANIMAL_ID=O.ANIMAL_ID)
ORDER BY ANIMAL_ID