-- 코드를 작성해주세요
SELECT ROUTE, 
concat(round(SUM(D_BETWEEN_DIST),1),'km') as TOTAL_DISTANCE, 
concat(ROUND(AVG(D_BETWEEN_DIST),2),'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY round(SUM(D_BETWEEN_DIST),1) DESC

