-- 2021년에 가입한 회원 중 상품 구매한 회원수와 구매비율(둘째자리"에서" 반올림)
# 년, 월 로 출력
# 년기준 오름차순 월기준 오름차순
SELECT 
DATE_FORMAT(sales_date,"%Y") as YEAR,
MONTH(sales_date) as MONTH,
COUNT(DISTINCT a.USER_ID) as PURCHASED_USERS,
round(COUNT(DISTINCT  a.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) as PURCHASED_RATIO

FROM USER_INFO a
JOIN ONLINE_SALE b
ON a.USER_ID=b.USER_ID 
WHERE YEAR(a.JOINED) = 2021

GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE)