-- 코드를 작성해주세요
# 1분기: 1,2,3// 2분기:4,5,6 // 3분기: 7,8,9// 4분기: 10,11,12
SELECT CASE 
WHEN MONTH(DIFFERENTIATION_DATE)<=3 THEN '1Q'
WHEN MONTH(DIFFERENTIATION_DATE) between 4 and 6 THEN '2Q'
WHEN MONTH(DIFFERENTIATION_DATE) between 7 and 9 THEN '3Q'
ELSE '4Q' 
END AS QUARTER,
COUNT(DISTINCT ID) as ECOLI_COUNT

# SELECT MONTH(DIFFERENTIATION_DATE)
FROM ECOLI_DATA
GROUP BY QUARTER