-- 코드를 입력하세요
# 공간을 두개이상 등록한 사람의 공간 정보, 아이디 순으로 조회
with HEAVY as (
SELECT HOST_ID
FROM PLACES 
GROUP BY HOST_ID
HAVING COUNT(ID)>=2)

SELECT *
FROM PLACES
WHERE HOST_ID in (SELECT HOST_ID FROM HEAVY)
ORDER BY ID

# SELECT HOST_ID
# FROM PLACES 
# GROUP BY HOST_ID
# HAVING COUNT(ID)>=2