# 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
JOIN PATIENT p
ON a.PT_NO=p.PT_NO
JOIN DOCTOR d
ON a.MDDR_ID=d.DR_ID
WHERE a.APNT_CNCL_YN='N' and a.MCDP_CD='CS' and a.APNT_YMD LIKE '2022-04-13%'
order by a.APNT_YMD 