-- 코드를 작성해주세요
SELECT DISTINCT a.ID,a.EMAIL,a.FIRST_NAME,a.LAST_NAME
# SELECT *
FROM DEVELOPERS a 
JOIN SKILLCODES b
# ON a의 SKILL_CODE에 b의 CODE가 포함되는 것
ON (a.SKILL_CODE&b.CODE)>0
WHERE b.CATEGORY='Front END' 
ORDER BY ID

