-- 코드를 입력하세요
with c as(SELECT COUNT(REVIEW_TEXT) as cnt, MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY cnt DESC
LIMIT 1)

SELECT a.MEMBER_NAME, b.REVIEW_TEXT, 
DATE_FORMAT(b.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE a 
JOIN REST_REVIEW b ON a.MEMBER_ID = b.MEMBER_ID
JOIN c c ON a.MEMBER_ID = c.MEMBER_ID
WHERE c.MEMBER_ID IS NOT NULL
ORDER BY b.REVIEW_DATE, b.REVIEW_TEXT