# 2022.01의 카테고리 별 도서 판매량, 캍고리명 기준으로 오름차순 정렬
SELECT a.CATEGORY, SUM(b.SALES) as TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b
ON a.BOOK_ID=b.BOOK_ID
WHERE YEAR(b.SALES_DATE)=2022 and MONTH(b.SALES_DATE)=1
GROUP BY a.CATEGORY
# HAVING 
ORDER BY 1