-- 코드를 작성해주세요
WITH m2 as (
select ID,
    CASE
    WHEN LENGTH IS NULL THEN 10
    WHEN LENGTH IS NOT NULL THEN LENGTH
    END as LENGTH2
FROM FISH_INFO
)


SELECT COUNT(DISTINCT b.ID) as FISH_COUNT,
MAX(b.LENGTH2) as MAX_LENGTH, 
a.FISH_TYPE
FROM FISH_INFO a
LEFT JOIN m2 b
ON a.ID=b.ID
GROUP BY FISH_TYPE
HAVING AVG(LENGTH2)>=33
ORDER BY FISH_TYPE ASC
